# top-level directory of our data
swift_data_dir: "~/Downloads/swift"
# horizon ID for Catalina C/2013 US10
jpl_horizons_id: "90004183"
# where to store stacked images
# stacked_image_dir: "stacked"
stacked_image_dir: "stacked_test"

solar_spectrum_path: "data/sorce_ssi_l3.csv"
effective_area_uw1_path: "data/swift_effective_areas/w1.arf"
effective_area_uvv_path: "data/swift_effective_areas/v.arf"
