name: swift_comet_pipeline

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy=1.23.5
  - scipy=1.10.1
  - astropy=5.1
  - astroquery=0.4.6
  - pandas=1.5.3
  - matplotlib=3.6.3
  - photutils=1.7.0
  - tqdm=4.65.0
  - pyarrow=11.0.0
