[project]
name = "sushipotato"
version = "0.0.1"
description = "Pipeline for determining water production rates from the Swift telescope's UVOT images"
requires-python = ">3.7"
classifiers = ["Programming Language :: Python :: 3",]
